name: flutter_template_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  get_cli: ^1.8.1
  cupertino_icons: ^1.0.6
  get: 4.7.2
  flutter_screenutil: ^5.9.3  #屏幕适配
  flutter_styled_toast: ^2.2.1    #全局消息弹窗
  logger: ^2.3.0              #日志管理
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

