name: flutter_template_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  get_cli: ^1.8.1
  cupertino_icons: ^1.0.6
  get: 4.7.2
  flutter_screenutil: ^5.9.3  #屏幕适配
  logger: ^2.3.0              #日志管理
  flutter_flavorizr: ^2.2.3   #环境管理
  mmkv: ^2.1.0                #本地存储
  flutter_gen_runner: ^5.4.0  #资源文件管理
  
  flutter: 
    sdk: flutter
  cherry_toast: ^1.12.0       #消息提示

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.8        #代码生成工具

flutter: 
  uses-material-design: true
  
  # 资源文件配置
  assets:
    - assets/images/
    - assets/icons/
    
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

